# Generated by Django 4.2.7 on 2023-12-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('seats', models.IntegerField()),
                ('shape', models.CharField(choices=[('rectangular', 'Прямоугольный'), ('oval', 'Овальный')], max_length=20)),
                ('horizontal_position', models.FloatField()),
                ('vertical_position', models.FloatField()),
                ('width_percent', models.FloatField()),
                ('length_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cat.table')),
            ],
        ),
    ]
