# Generated by Django 4.2.7 on 2023-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cat', '0002_table_is_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipe_photos/')),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
    ]
