# Generated by Django 4.2.7 on 2023-12-24 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cat', '0003_recipe_remove_table_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='config\\menu_photos'),
        ),
    ]
